version: "3.7"

volumes:
  database_data:
  parallax:

networks:
  default:

services:

  parallax:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/parallax
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - parallax/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=parallax.settings
      - DEBUG=True
    networks:
      - default

  tests:
    build: .
    command: coverage run -m pytest
    volumes:
      - .:/parallax
    env_file:
      - parallax/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=parallax.test_settings
    networks:
      - default
