version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.1.0
jobs:
  build:
    docker:
    - image: cimg/python:3.10.6
    - image: cimg/postgres:14.0
      environment:
        POSTGRES_USER: parallax
        POSTGRES_DB: parallax
        POSTGRES_PASSWORD: parallax
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          environment:
            DJANGO_SETTINGS_MODULE: 'parallax.test_settings'
          command: coverage run -m pytest;
      - coveralls/upload:
          parallel: true
workflows:
  test-workflow:
    jobs:
    - build
