version: 2.1
orbs:
  coveralls: coveralls@2.1.0
jobs:
  build:
    docker:
    - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          environment: COVERALLS_REPO_TOKEN
          command: |
            $HOME/.local/bin/coverage run -m pytest
workflows:
  test-workflow:
    jobs:
    - build
