SERVER_DEFAULTS = {
    'PUBLIC_PORT': 2500,
    'UPLOAD_LIMIT': 10,
    'SCHEDULED_SCAN_INTERVAL': 60,  # minutes
    'QUEUE_RETENTION_INTERVAL': 28,  # days
    'MAX_QUEUE_SIZE': 30,
    'PLAYED_THRESHOLD': 90, # percent
    'PAUSED_TERMINATION_LIMIT': 10,  # minutes
    'MAX_STREAM_COUNT': -1,
    'MAX_TRANSCODE_COUNT': -1,
}
