# Generated by Django 4.2.8 on 2023-12-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('name', 'owner')},
        ),
    ]
