# Generated by Django 4.1.7 on 2023-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='type',
            field=models.CharField(choices=[('cast', 'cast'), ('crew', 'crew')], max_length=4, verbose_name='type'),
        ),
    ]
