# Generated by Django 4.2.8 on 2023-12-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_movielibrary_authorized_users_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='type',
            field=models.CharField(choices=[('crew', 'crew'), ('cast', 'cast')], max_length=4, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='library.videolibrary'),
        ),
    ]
