# Generated by Django 4.1.7 on 2023-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='type',
            field=models.CharField(choices=[('cast', 'cast'), ('crew', 'crew')], max_length=4, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='country'),
        ),
    ]
