# Generated by Django 4.1.7 on 2023-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_credit_type_alter_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='filepath',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='filepath'),
        ),
    ]
