# Generated by Django 4.1.7 on 2023-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_movie_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='filepath',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='filepath'),
        ),
        migrations.AddField(
            model_name='video',
            name='filepath',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='filepath'),
        ),
    ]
