# Generated by Django 4.1.7 on 2023-04-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_episode_filepath_video_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
